# Generated by Django 2.0.5 on 2018-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkrundata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_junior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
