# Generated by Django 2.0.7 on 2018-07-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkrundata', '0002_auto_20180717_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_junior',
            new_name='is_juniors',
        ),
    ]
